language: python
cache: pip

jobs:
  include:
  - stage: Testing with Python 3.6
    python: '3.6'
    install:
      - pip install -r requirements-dev.txt
      - pip install -e .
    script:
      - python -m pytest
      - mypy jikanpy
  - stage: Testing with Python 3.7
    python: '3.7'
    sudo: required
    dist: xenial
    install:
      - pip install -r requirements-dev.txt
      - pip install -e .
      - pip install pytest-cov codecov
    script:
      - python -m pytest
      - mypy jikanpy
    after_success:
     - pytest --cov jikanpy tests/
     - codecov
