language: python
cache: pip

jobs:
  include:
    - stage: Testing with Python 3.6
      python: '3.6'
      install:
        - pip install -r requirements-dev.txt
        - pip install -e .
      script: python -m pytest
    - stage: Testing with Python 3.7
      python: '3.7'
      dist: xenial
      install:
        - pip install -r requirements-dev.txt
        - pip install -e .
        - pip install pytest-cov
      script:
        - pytest --cov jikanpy tests/
        - mypy jikanpy
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL_PASS
      after_failure:
        - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL_FAIL
